import { COMMON_EQUATION_INPUTS } from './constants';
import type { PillarStrengthEquation } from './types';

const sourceTable = [
  'Reference slides folder: pillar_strength_for_reference_slides',
  'Suorineni_ALL_Equations.pdf, Tables 2 and 3, Suorineni (2013) equation summaries reproduced in Suorineni (2014).',
];

const ratioVariables = [
  { symbol: 'W, w', description: 'Pillar width used by the equation', unit: 'm' },
  { symbol: 'H, h', description: 'Pillar height used by the equation', unit: 'm' },
  {
    symbol: 'sigma_p',
    description: 'Estimated pillar strength',
    unit: 'MPa',
  },
];

const ucsVariable = {
  symbol: 'sigma_c',
  description: 'Compressive strength or equation-specific strength constant',
  unit: 'MPa',
};

export const pillarStrengthEquations: PillarStrengthEquation[] = [
  {
    id: 'johnson-1897',
    name: 'Johnson',
    year: '1897',
    reference: 'Johnson (1897)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = sigma_c [0.778 + 0.222(w / h)]',
    requiredInputs: [COMMON_EQUATION_INPUTS.ucsMpa],
    variableDefinitions: [...ratioVariables, ucsVariable],
    assumptions: ['Uses a dimensionless width-to-height correction on sigma_c.'],
    limitations: [
      'Calibration context is not expanded in the slide table.',
      'Use only when sigma_c is appropriate for the selected rock and specimen basis.',
    ],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'linearUcsRatio',
  },
  {
    id: 'carpenter-1901',
    name: 'Carpenter',
    year: '1901',
    reference: 'Carpenter (1901)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = k / sqrt(h)',
    requiredInputs: [COMMON_EQUATION_INPUTS.coefficientK],
    variableDefinitions: [
      ...ratioVariables,
      { symbol: 'k', description: 'Calibrated equation coefficient', unit: 'MPa.m^0.5' },
    ],
    assumptions: ['Coefficient k must be supplied on a metric basis.'],
    limitations: ['The slide does not define k or the original calibration units.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'coefficientOverSqrtHeight',
  },
  {
    id: 'bunting-1912',
    name: 'Bunting',
    year: '1912',
    reference: 'Bunting (1912)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = 1000[0.70 + 0.30(w / h)] psi, converted to MPa',
    requiredInputs: [],
    variableDefinitions: ratioVariables,
    assumptions: [
      'The paper table lists a factor of safety of 2.5.',
      'The historical coefficient is treated as psi and converted to MPa.',
    ],
    limitations: [
      'Original calibration context and specimen basis are not expanded in the paper table.',
    ],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'bunting1912',
  },
  {
    id: 'greenwald-howarth-hartman-1939',
    name: 'Greenwald, Howarth and Hartman',
    year: '1939',
    reference: 'Greenwald, Howarth and Hartman (1939)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = k sqrt(W / H)',
    requiredInputs: [COMMON_EQUATION_INPUTS.coefficientK],
    variableDefinitions: [
      ...ratioVariables,
      { symbol: 'k', description: 'Calibrated equation coefficient', unit: 'MPa' },
    ],
    assumptions: ['Uses a square-root width-to-height ratio correction.'],
    limitations: ['The slide does not define k or its calibration basis.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'kSqrtWidthHeightRatio',
  },
  {
    id: 'greenwald-howarth-hartman-1941',
    name: 'Greenwald, Howarth and Hartman',
    year: '1941',
    reference: 'Greenwald, Howarth and Hartman (1941)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = 2800[W^0.5 / H^(5/6)] psi, with W and H in inches',
    requiredInputs: [],
    variableDefinitions: ratioVariables,
    assumptions: [
      'The historical inch/psi form is evaluated internally and converted to MPa.',
    ],
    limitations: [
      'Original calibration context and specimen basis are not expanded in the paper table.',
    ],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'greenwald1941',
  },
  {
    id: 'obert-duvall-1946',
    name: 'Obert and Duvall',
    year: '1946',
    reference: 'Obert and Duvall (1946)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = sigma_c [0.778 + 0.222(w / h)]',
    requiredInputs: [COMMON_EQUATION_INPUTS.ucsMpa],
    variableDefinitions: [...ratioVariables, ucsVariable],
    assumptions: ['Uses the same readable form as Johnson in the slide table.'],
    limitations: ['The slide lists an FS range of 2 to 4 but does not make it design logic.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'linearUcsRatio',
  },
  {
    id: 'modified-obert-duvall-1967',
    name: 'Modified Obert and Duvall',
    year: '1967',
    reference: 'Modified Obert and Duvall (1967)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText:
      'Same as Obert and Duvall, but sigma_c determined from 1.5 m side-length cubes instead of 250 mm.',
    requiredInputs: [COMMON_EQUATION_INPUTS.ucsMpa],
    variableDefinitions: [...ratioVariables, ucsVariable],
    assumptions: ['Use sigma_c from the specimen basis described in the slide row.'],
    limitations: ['Specimen-size basis must be selected consistently by the user.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'linearUcsRatio',
  },
  {
    id: 'holland-gaddy-1964',
    name: 'Holland-Gaddy',
    year: '1964',
    reference: 'Holland-Gaddy (1964)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = k sqrt(w) / h; k = sigma_c sqrt(D)',
    requiredInputs: [
      COMMON_EQUATION_INPUTS.ucsMpa,
      COMMON_EQUATION_INPUTS.specimenDiameterM,
    ],
    variableDefinitions: [
      ...ratioVariables,
      ucsVariable,
      { symbol: 'D', description: 'Reference specimen size', unit: 'm' },
    ],
    assumptions: ['Uses metric W, H, and D consistently.'],
    limitations: ['The slide does not expand D beyond the formula note.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'hollandGaddy',
  },
  {
    id: 'bieniawski-1967-1969-small',
    name: 'Bieniawski small-width variant',
    year: '1967/1969',
    reference: 'Bieniawski (1967, 1969)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal, w < 60 inches in the slide table',
    formulaText:
      'sigma_p = 1100[w^0.16 / h^0.55] psi, w < 60 inches; w and h converted from metres to inches',
    requiredInputs: [],
    variableDefinitions: ratioVariables,
    assumptions: ['Historical inch/psi form is converted to MPa.'],
    limitations: [
      'Use only within the w < 60 inches range unless deliberately comparing equations.',
    ],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'bieniawskiSmall1967',
  },
  {
    id: 'bieniawski-1967-1969-large',
    name: 'Bieniawski large-width variant',
    year: '1967/1969',
    reference: 'Bieniawski (1967, 1969)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal, w > 60 inches in the slide table',
    formulaText: 'sigma_p = [400 + 200(w / h)] psi, w > 60 inches; converted to MPa',
    requiredInputs: [],
    variableDefinitions: ratioVariables,
    assumptions: ['Historical psi form is converted to MPa.'],
    limitations: [
      'Use only within the w > 60 inches range unless deliberately comparing equations.',
    ],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'bieniawskiLarge1967',
  },
  {
    id: 'bieniawski-1981-shape-factor',
    name: 'Bieniawski shape-factor variant',
    year: '1981',
    reference: 'Bieniawski (1981)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = sigma_c [0.64 + 0.36(w / h)]^alpha',
    requiredInputs: [COMMON_EQUATION_INPUTS.ucsMpa, COMMON_EQUATION_INPUTS.alpha],
    variableDefinitions: [
      ...ratioVariables,
      ucsVariable,
      { symbol: 'alpha', description: 'Calibration exponent from the equation', unit: '-' },
    ],
    assumptions: ['Alpha is user-supplied because the slide shows the symbol but not a value.'],
    limitations: ['Use only with a defensible alpha for the rock type and database.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'bieniawski1981',
  },
  {
    id: 'salamon-munro-1967',
    name: 'Salamon and Munro',
    year: '1967',
    reference: 'Salamon and Munro (1967)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Coal / soft rock table entry',
    formulaText: 'sigma_p = sigma_c [W^0.46 / H^0.66]',
    requiredInputs: [COMMON_EQUATION_INPUTS.strengthConstantMpa],
    variableDefinitions: [
      ...ratioVariables,
      {
        symbol: 'sigma_c',
        description: 'Coal strength constant shown in the slide equation',
        unit: 'MPa',
      },
    ],
    assumptions: ['Uses W and H in metres with a metric strength constant.'],
    limitations: [
      'The strength constant must match the dimensional basis of W^0.46/H^0.66.',
    ],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'salamonMunro',
  },
  {
    id: 'modified-salamon-munro-1967',
    name: 'Modified Salamon and Munro',
    year: '1967',
    reference: 'Modified Salamon and Munro (1967)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Coal / soft rock table entry',
    formulaText:
      'sigma_p = sigma_cs (W_p / W_s)^0.46 / (H_p / H_s)^0.66',
    requiredInputs: [
      COMMON_EQUATION_INPUTS.ucsMpa,
      COMMON_EQUATION_INPUTS.specimenWidthM,
      COMMON_EQUATION_INPUTS.specimenHeightM,
    ],
    variableDefinitions: [
      ...ratioVariables,
      {
        symbol: 'sigma_cs',
        description: 'Specimen compressive strength used for scaling',
        unit: 'MPa',
      },
      { symbol: 'W_s, H_s', description: 'Specimen width and height', unit: 'm' },
    ],
    assumptions: [
      'Paper table row lists an FS range of 1.31-1.88.',
      'Height scaling is implemented as a denominator to preserve the Salamon-Munro height effect.',
    ],
    limitations: [
      'Confirm the specimen basis before using this row for design.',
    ],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'modifiedSalamonMunro',
  },
  {
    id: 'salamon-1982',
    name: 'Salamon',
    year: '1982',
    reference: 'Salamon (1982)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Coal / soft rock table entry',
    formulaText:
      'sigma_p = k V^-0.0667 R0^0.5933 {0.5933/epsilon [(R/R0)^epsilon - 1] + 1}',
    requiredInputs: [
      COMMON_EQUATION_INPUTS.coefficientK,
      COMMON_EQUATION_INPUTS.referenceRatio,
      COMMON_EQUATION_INPUTS.epsilon,
    ],
    variableDefinitions: [
      ...ratioVariables,
      { symbol: 'V', description: 'Pillar volume from entered geometry', unit: 'm3' },
      { symbol: 'R', description: 'Pillar width-to-height ratio W/H', unit: '-' },
      { symbol: 'R0', description: 'Reference width-to-height ratio', unit: '-' },
      { symbol: 'epsilon', description: 'Curvature exponent', unit: '-' },
    ],
    assumptions: ['Uses V = W x L x H and R = W/H from the current geometry.'],
    limitations: ['k, R0, and epsilon must match the calibration basis of the equation.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'salamon1982',
  },
  {
    id: 'wilson-1972',
    name: 'Wilson',
    year: '1972',
    reference: 'Wilson (1972)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = sigma_c + sigma_3 tan(beta)',
    requiredInputs: [
      COMMON_EQUATION_INPUTS.ucsMpa,
      COMMON_EQUATION_INPUTS.sigma3Mpa,
      COMMON_EQUATION_INPUTS.frictionAngleDeg,
    ],
    variableDefinitions: [
      ucsVariable,
      { symbol: 'sigma_3', description: 'Confining stress', unit: 'MPa' },
      { symbol: 'beta', description: 'Angle in tangent term', unit: 'degrees' },
    ],
    assumptions: ['Uses beta in degrees in this calculator.'],
    limitations: ['The slide does not describe how sigma_3 should be estimated for pillars.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'wilson',
  },
  {
    id: 'hardy-agapito-1975',
    name: 'Hardy and Agapito',
    year: '1975',
    reference: 'Hardy and Agapito (1975)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText:
      'sigma_p = sigma_cs (W_p / W_s)^0.597 / (H_p / H_s)^0.951',
    requiredInputs: [
      COMMON_EQUATION_INPUTS.ucsMpa,
      COMMON_EQUATION_INPUTS.specimenWidthM,
      COMMON_EQUATION_INPUTS.specimenHeightM,
    ],
    variableDefinitions: [
      ...ratioVariables,
      {
        symbol: 'sigma_cs',
        description: 'Specimen compressive strength used for scaling',
        unit: 'MPa',
      },
      { symbol: 'W_s, H_s', description: 'Specimen width and height', unit: 'm' },
    ],
    assumptions: [
      'Height scaling is implemented as a denominator so strength decreases with increasing pillar height.',
    ],
    limitations: ['Confirm the specimen basis before using this row for design.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'hardyAgapito1975',
  },
  {
    id: 'wardell-1976',
    name: 'Wardell',
    year: '1976',
    reference: 'Wardell (1976)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = a[1 / H] + b[W / H]^2',
    requiredInputs: [
      COMMON_EQUATION_INPUTS.coefficientA,
      COMMON_EQUATION_INPUTS.coefficientB,
    ],
    variableDefinitions: [
      ...ratioVariables,
      { symbol: 'a, b', description: 'Calibrated empirical coefficients' },
    ],
    assumptions: ['Coefficients a and b are supplied by the user in metric-compatible units.'],
    limitations: ['The slide does not give coefficient values.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'wardell',
  },
  {
    id: 'wang-1977',
    name: 'Wang et al.',
    year: '1977',
    reference: 'Wang et al. (1977)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = sigma_c [0.78 + 0.22(w / h)]',
    requiredInputs: [COMMON_EQUATION_INPUTS.ucsMpa],
    variableDefinitions: [...ratioVariables, ucsVariable],
    assumptions: ['Uses a dimensionless width-to-height correction on sigma_c.'],
    limitations: ['Calibration context is not expanded in the slide table.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'wangLinearUcsRatio',
  },
  {
    id: 'bieniawski-1981-1983',
    name: 'Bieniawski',
    year: '1981/83',
    reference: 'Bieniawski (1981/83)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = sigma_c [0.64 + 0.36(W / H)]^alpha',
    requiredInputs: [COMMON_EQUATION_INPUTS.ucsMpa, COMMON_EQUATION_INPUTS.alpha],
    variableDefinitions: [
      ...ratioVariables,
      ucsVariable,
      { symbol: 'alpha', description: 'Calibration exponent from the equation', unit: '-' },
    ],
    assumptions: ['Alpha is user-supplied because the slide shows the symbol but not a value.'],
    limitations: ['The slide lists an FS value of 1.5 but does not make it design logic.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'bieniawski1981',
  },
  {
    id: 'hustrulid-swanson-1981',
    name: 'Hustrulid and Swanson',
    year: '1981',
    reference: 'Hustrulid and Swanson (1981)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'sigma_p = k / H^0.50 [W / H]^0.50; k = sigma_c D^0.50',
    requiredInputs: [
      COMMON_EQUATION_INPUTS.ucsMpa,
      COMMON_EQUATION_INPUTS.specimenDiameterM,
    ],
    variableDefinitions: [
      ...ratioVariables,
      ucsVariable,
      { symbol: 'D', description: 'Reference specimen size', unit: 'm' },
    ],
    assumptions: ['Uses metric W, H, and D consistently.'],
    limitations: ['The slide does not expand D beyond the formula note.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'hustrulidSwanson',
  },
  {
    id: 'agapito-hardy-1982',
    name: 'Agapito and Hardy',
    year: '1982',
    reference: 'Agapito and Hardy (1982)',
    rockCategory: 'coal-soft-rock',
    applicableRockType: 'Soft rock / coal table entry',
    formulaText: 'Complex. See reference for details.',
    requiredInputs: [],
    variableDefinitions: ratioVariables,
    assumptions: [],
    limitations: ['The slide intentionally does not provide the equation details.'],
    status: 'placeholder',
    statusNote:
      'This equation is listed from the reference slides but is not fully parameterized yet.',
    sourceNotes: sourceTable,
    // TODO: Fill in after obtaining the Agapito and Hardy equation details.
  },
  {
    id: 'hedley-grant-1972',
    name: 'Hedley and Grant',
    year: '1972',
    reference: 'Hedley and Grant (1972)',
    rockCategory: 'hard-rock',
    applicableRockType: 'Quartzite; slide table lists sigma_c = 230 MPa',
    formulaText: 'sigma_p = 179[W^0.5 / H^0.75]',
    requiredInputs: [],
    variableDefinitions: ratioVariables,
    assumptions: ['Uses W and H in metres with the coefficient shown in the hard-rock slide table.'],
    limitations: ['Adapted hard-rock equation; use only for a similar calibration context.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'hedleyGrant',
  },
  {
    id: 'hoek-brown-1980',
    name: 'Hoek and Brown',
    year: '1980',
    reference: 'Hoek and Brown (1980)',
    rockCategory: 'hard-rock',
    applicableRockType: 'Hard rock failure criterion listed in the slide table',
    formulaText: 'sigma_1 = sigma_3 + sqrt(m sigma_c sigma_3 + s sigma_c^2)',
    requiredInputs: [
      COMMON_EQUATION_INPUTS.ucsMpa,
      COMMON_EQUATION_INPUTS.sigma3Mpa,
      COMMON_EQUATION_INPUTS.hoekBrownM,
      COMMON_EQUATION_INPUTS.hoekBrownS,
    ],
    variableDefinitions: [
      ucsVariable,
      { symbol: 'sigma_1', description: 'Major principal stress at failure', unit: 'MPa' },
      { symbol: 'sigma_3', description: 'Minor principal stress', unit: 'MPa' },
      { symbol: 'm, s', description: 'Hoek-Brown material constants' },
    ],
    assumptions: ['Included because it appears in the hard-rock slide table.'],
    limitations: [
      'This is a rock failure criterion, not a room-and-pillar tributary-area strength equation.',
    ],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'hoekBrown',
  },
  {
    id: 'hedley-roxburgh-muppalaneni-1984',
    name: 'Hedley, Roxburgh and Muppalaneni',
    year: '1984',
    reference: 'Hedley, Roxburgh and Muppalaneni (1984)',
    rockCategory: 'hard-rock',
    applicableRockType: 'Quartzite; slide table lists sigma_c = 230 MPa',
    formulaText: 'sigma_p = 133[W^0.5 / H^0.75]',
    requiredInputs: [],
    variableDefinitions: ratioVariables,
    assumptions: ['Name spelling follows the clearest readable slide text.'],
    limitations: ['Use only for a similar calibration context.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'hedleyRoxburghMuppalaneni',
  },
  {
    id: 'kimmelmann-hyde-madgwick-1984',
    name: 'Kimmelmann, Hyde and Madgwick',
    year: '1984',
    reference: 'Kimmelmann, Hyde and Madgwick (1984)',
    rockCategory: 'hard-rock',
    applicableRockType: 'Metasediments; slide table lists sigma_c = 94 MPa',
    formulaText: 'sigma_p = 65[W^0.46 / H^0.66]',
    requiredInputs: [],
    variableDefinitions: ratioVariables,
    assumptions: ['Uses W and H in metres with the coefficient shown in the hard-rock slide table.'],
    limitations: ['Use only for a similar calibration context.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'kimmelmannHydeMadgwick',
  },
  {
    id: 'krauland-soder-1987',
    name: 'Krauland and Soder',
    year: '1987',
    reference: 'Krauland and Soder (1987)',
    rockCategory: 'hard-rock',
    applicableRockType: 'Limestone; slide table lists sigma_c = 100 MPa',
    formulaText: 'sigma_p = 35.4[0.778 + 0.222(W / H)]',
    requiredInputs: [],
    variableDefinitions: ratioVariables,
    assumptions: ['Uses the coefficient shown in the hard-rock slide table.'],
    limitations: ['Use only for a similar calibration context.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'kraulandSoder',
  },
  {
    id: 'potvin-hudyma-miller-1989',
    name: 'Potvin, Hudyma and Miller',
    year: '1989',
    reference: 'Potvin, Hudyma and Miller (1989)',
    rockCategory: 'hard-rock',
    applicableRockType: 'Canadian Shield hard rocks',
    formulaText: 'sigma_p = 0.42 sigma_c [W / H]',
    requiredInputs: [COMMON_EQUATION_INPUTS.ucsMpa],
    variableDefinitions: [...ratioVariables, ucsVariable],
    assumptions: ['Uses a dimensionless W/H multiplier on sigma_c.'],
    limitations: ['Use only for a similar hard-rock calibration context.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'potvinHudymaMiller',
  },
  {
    id: 'sjoberg-1992',
    name: 'Sjoberg',
    year: '1992',
    reference: 'Sjoberg (1992)',
    rockCategory: 'hard-rock',
    applicableRockType: 'Limestone / skarn; slide table lists sigma_c = 240 MPa',
    formulaText: 'sigma_p = 74[0.778 + 0.222(W / H)]',
    requiredInputs: [],
    variableDefinitions: ratioVariables,
    assumptions: ['Uses the coefficient shown in the hard-rock slide table.'],
    limitations: ['Use only for a similar calibration context.'],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'sjoberg',
  },
  {
    id: 'martin-1993',
    name: 'Martin',
    year: '1993',
    reference: 'Martin (1993)',
    rockCategory: 'hard-rock',
    applicableRockType: 'Hard rock table entry',
    formulaText: 'sigma_1 = sigma_3 + sqrt(s) sigma_c',
    requiredInputs: [
      COMMON_EQUATION_INPUTS.ucsMpa,
      COMMON_EQUATION_INPUTS.sigma3Mpa,
      COMMON_EQUATION_INPUTS.martinS,
    ],
    variableDefinitions: [
      ucsVariable,
      { symbol: 's', description: 'Material or rock mass constant' },
      { symbol: 'sigma_3', description: 'Minor principal stress', unit: 'MPa' },
    ],
    assumptions: [
      'Default s = 0.1089 gives sqrt(s) = 0.33, matching the table rock mass-intact strength ratio.',
    ],
    limitations: [
      'This is a hard-rock failure criterion row, not a direct tributary-area pillar equation.',
    ],
    status: 'implemented',
    sourceNotes: sourceTable,
    calculatorId: 'martin1993',
  },
  {
    id: 'lunder-pakalnis-1997',
    name: 'Lunder and Pakalnis',
    year: '1997',
    reference: 'Lunder and Pakalnis (1997)',
    rockCategory: 'hard-rock',
    applicableRockType: 'Hard rocks',
    formulaText:
      'sigma_p = 0.44 sigma_c [0.68 + 0.52 kappa], with kappa calculated from Cpav and W/H',
    requiredInputs: [COMMON_EQUATION_INPUTS.ucsMpa],
    variableDefinitions: [
      ucsVariable,
      {
        symbol: 'kappa',
        description: 'Confinement term used by Lunder and Pakalnis',
        unit: '-',
      },
    ],
    assumptions: [
      'Cpav and kappa are calculated from W/H by default.',
      'Manual kappa override is available in the calculator for site-calibrated workflows.',
    ],
    limitations: [
      'The referenced hard-rock design chart in the PDF warns that empirical curves can be misinterpreted.',
      'Site calibration is still recommended before using the confinement formula for design.',
    ],
    status: 'implemented',
    sourceNotes: [
      ...sourceTable,
      'EMPIRICALMETHODSINMININGGEOMECHANICS-REFLECTIONS.pdf, hard rock pillar design chart discussion.',
    ],
    calculatorId: 'lunderPakalnis',
  },
  {
    id: 'custom-power-law',
    name: 'Custom power-law equation',
    reference: 'User-defined',
    rockCategory: 'custom',
    applicableRockType: 'Custom calibration',
    formulaText: 'Strength = multiplier x k x W^alpha / H^beta',
    requiredInputs: [
      COMMON_EQUATION_INPUTS.coefficientK,
      COMMON_EQUATION_INPUTS.alpha,
      COMMON_EQUATION_INPUTS.beta,
      COMMON_EQUATION_INPUTS.customMultiplier,
    ],
    variableDefinitions: [
      ...ratioVariables,
      { symbol: 'k', description: 'User-defined strength coefficient' },
      { symbol: 'alpha, beta', description: 'User-defined exponents' },
    ],
    assumptions: ['All coefficients and exponents are user-supplied.'],
    limitations: ['Custom equations are only as reliable as their calibration.'],
    status: 'implemented',
    sourceNotes: ['Custom option requested for incomplete literature coverage.'],
    calculatorId: 'customPowerLaw',
  },
];

export function getPillarStrengthEquation(
  equationId: string
): PillarStrengthEquation | undefined {
  return pillarStrengthEquations.find((equation) => equation.id === equationId);
}
